2018-04-03 10:58:09,835  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 10:58:09――System.Data.Entity.Infrastructure.DbUpdateException：An error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.AddEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 194
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 50
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageAn error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 10:58:10,324  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 10:58:10――System.Data.Entity.Infrastructure.DbUpdateException：An error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.AddEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 194
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 50
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageAn error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 10:58:42,359  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 10:58:42――System.Data.Entity.Infrastructure.DbUpdateException：An error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.AddEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 194
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 50
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageAn error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 11:14:38,154  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 11:14:38――System.Data.Entity.Infrastructure.DbUpdateConcurrencyException：Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.UpdateEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 404
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 60
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageStore update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 11:23:33,137  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 11:23:33――System.Data.Entity.Infrastructure.DbUpdateException：An error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.AddEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 194
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 50
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageAn error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 11:25:57,286  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 11:25:57――System.Data.Entity.Infrastructure.DbUpdateException：An error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Internal.InternalContext.SaveChanges()
   在 WisdomScenic.Project.Domain.EFContext.WisdomScenicDbContext.SaveChanges() 位置 E:\Project\Wisdom.Trip\Web.Service\WisDomScenic.Project.Domain\EFContext\WisdomScenicDbContext.cs:行号 73
   在 WisdomScenic.Project.DAL.BaseRepository`1.AddEntity(T entity, E_DbClassify dbClassify, String businessName, Boolean logChangesDuringSave, String moduleKey) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.DAL\BaseRepository.cs:行号 194
   在 WisdomScenic.Project.BLL.Articles.T_ArticleService.AddOrEditArticle(ArticleDto dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleService.cs:行号 50
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<>c__DisplayClass3_0.<AddOrEditArticle>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleController.<AddOrEditArticle>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()EntityFrameworkactionExecutedContext.Exception.InnerException.MessageAn error occurred while updating the entries. See the inner exception for details.――堆栈信息：   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   在 System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   在 System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   在 System.Data.Entity.Internal.InternalContext.SaveChanges()EntityFramework
2018-04-03 15:07:05,625  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 15:07:05――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.BLL.Articles.T_ArticleCategoryService.GetArticleCategoryPageList(GridDataRequest req) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleCategoryService.cs:行号 48
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleCategoryController.<>c__DisplayClass3_0.<GetArticleCategoryPageList>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleCategoryController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleCategoryController.<GetArticleCategoryPageList>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleCategoryController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()WisdomScenic.Project.BLL
2018-04-03 15:07:07,995  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-04-03 15:07:07――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.BLL.Articles.T_ArticleCategoryService.GetArticleCategoryPageList(GridDataRequest req) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Articles\T_ArticleCategoryService.cs:行号 48
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleCategoryController.<>c__DisplayClass3_0.<GetArticleCategoryPageList>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleCategoryController.cs:行号 54
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Content.ArticleCategoryController.<GetArticleCategoryPageList>d__3.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Content\ArticleCategoryController.cs:行号 51
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()WisdomScenic.Project.BLL
